# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0faa5df65beab736ac023ddad4d219e343ce50a2d773019adcf083a3a807a6fac595c130fbcb0093cbfd6a9d5eeb349c9ec6adf9f2aa56c117b1e8a11d7acd9a

test:
  secret_key_base: c8a7703a81fc7ad564096f224072f7900c5153a92cb444cf66452ea6e7e61b16b4508149915045c6b2ca01bceec1278d46e218f46cdc150b5732ab415c22b0e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
